export const COLLECTION_NAMES = {
  USERS: "users",
  BUILDINGS: "buildings",
  FLOORS: "floors",
  EQUIPMENT: "equipment",
  FIRE_DRILLS: "fireDrills",
  INSPECTION_TEMPLATES: "inspectionTemplates",
  INSPECTIONS: "inspections",
  INSPECTION_RESULTS: "inspectionResults",
  EQUIPMENT_HISTORY: "equipmentHistory",
  ISSUES: "issues",
  ISSUE_COMMENTS: "issueComments",
  CLOSURE_VERIFICATIONS: "closureVerifications",
  NOTIFICATIONS: "notifications",
  REPORTS: "reports",
  AI_AUDIT_LOGS: "aiAuditLogs",
  AI_PRIORITY_POLICIES: "aiPriorityPolicies",
  CUSTOMER_FEEDBACK_THREADS: "customerFeedbackThreads",
  CUSTOMER_FEEDBACK_MESSAGES: "customerFeedbackMessages"
};
